interface ITypes {
    INPUT_CHANGE: string;
    DROPDOWN_CHANGE: string;
    DATE_PICKER_CHANGE: string;
    TIME_PICKER_CHANGE: string;
    COMBO_BOX_CHANGE: string;
    PRICE_CHANGE: string;
    QUANTITY_CHANGE: string;
    RESET_STATE: string;
}

export const types: ITypes = {
    INPUT_CHANGE: "INPUT_CHANGE",
    DROPDOWN_CHANGE: "DROPDOWN_CHANGE",
    DATE_PICKER_CHANGE: "DATE_PICKER_CHANGE",
    TIME_PICKER_CHANGE: "TIME_PICKER_CHANGE",
    COMBO_BOX_CHANGE: "COMBO_BOX_CHANGE",
    PRICE_CHANGE: "PRICE_CHANGE",
    QUANTITY_CHANGE: "QUANTITY_CHANGE",
    RESET_STATE: "RESET_STATE",
};
